environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm prune

test_script:
  - npm test

build: off

cache:
  - node_modules
